ROBUST_MIN_VALIDATION_SELECTION = 1.5
ROBUST_MIN_VALIDATION_PROFIT = 0.02
ROBUST_MAX_VALIDATION_DRAWDOWN = 0.03
ROBUST_MIN_VALIDATION_TRADES = 10.0
ROBUST_MAX_ABS_SELECTION_GAP = 1.5

SPECIALIST_MIN_VALIDATION_SELECTION = 8.0
SPECIALIST_MIN_VALIDATION_PROFIT = 0.03
SPECIALIST_MAX_VALIDATION_DRAWDOWN = 0.12
SPECIALIST_MIN_VALIDATION_TRADES = 10.0
SPECIALIST_MAX_ABS_SELECTION_GAP = 20.0
SPECIALIST_MIN_DATASET_PROFIT = -0.01
